### ISSUE TITLE
failed to mount a PVC on Nimble

### ISSUE THREAD

**Issue by sw34** [hpe-storage/csi-driver#224]
In a Rancher 2,5.2 environment I created a new cluster and installed and configured the csi driver per the instructions using the version 1.3.0 of the app (ver 1.3.1 failed with a yaml error)

Nimble OS 5.2.1.400

this is my storageClass

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: hpe-standard
provisioner: csi.hpe.com
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: hpe-nimble-wec-prod
  csi.storage.k8s.io/controller-expand-secret-namespace: hpe-csi-driver
  csi.storage.k8s.io/controller-publish-secret-name: hpe-nimble-wec-prod
  csi.storage.k8s.io/controller-publish-secret-namespace: hpe-csi-driver
  csi.storage.k8s.io/fstype: xfs
  csi.storage.k8s.io/node-publish-secret-name: hpe-nimble-wec-prod
  csi.storage.k8s.io/node-publish-secret-namespace: hpe-csi-driver
  csi.storage.k8s.io/node-stage-secret-name: hpe-nimble-wec-prod
  csi.storage.k8s.io/node-stage-secret-namespace: hpe-csi-driver
  csi.storage.k8s.io/provisioner-secret-name: hpe-nimble-wec-prod
  csi.storage.k8s.io/provisioner-secret-namespace: hpe-csi-driver
  description: Volume created by the HPE CSI Driver for Kubernetes
  destroyOnDelete: "true"
  folder: rancher-prod
  performancePolicy: "DockerDefault"
reclaimPolicy: Delete
allowVolumeExpansion: true
```

To test I created a PVC using the following:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hpe-standard
```

and a Pod using:

```
kind: Pod
apiVersion: v1
metadata:
  name: my-pod1
  namespace: default
spec:
  containers:
    - name: pod-datelog-2
      image: debian
      command: ["bin/sh"]
      args: ["-c", "while true; do date >> /data/mydata.txt; sleep 1; done"]
      volumeMounts:
        - name: export1
          mountPath: /data
  volumes:
    - name: export1
      persistentVolumeClaim:
        claimName: my-test-pvc
```

all basically taken from the SCOD install instructions.

The POD initially reported the following as an event:

```
MountVolume.MountDevice failed for volume "pvc-2f0b2279-72a9-4c6a-bfd8-fd5fc38ca230" : rpc error: code = Unavailable desc = Failed to get storage provider from secrets, Post http://nimble-csp-svc:8080/containers/v1/tokens: dial tcp: i/o timeout
```

which I overcame by using the ClusterIP in the secret as per #185 instead of serviceName

Now I get:

```
MountVolume.MountDevice failed for volume "pvc-2f0b2279-72a9-4c6a-bfd8-fd5fc38ca230" : rpc error: code = Internal desc = Failed to stage volume 0636cf84f4aa9b1ea5000000000000000000000051, err: rpc error: code = Internal desc = Error creating device for volume 0636cf84f4aa9b1ea5000000000000000000000051, err: device not found with serial edc309352b5720cc6c9ce900519a549c or target
```

even though the volume does exist on the Nimble.

logs from the nimble-csp are attached as are the details from "my-pod1" and the PVC

[nimble-csp.txt](https://github.com/hpe-storage/csi-driver/files/5542823/nimble-csp.txt)
[pod1.txt](https://github.com/hpe-storage/csi-driver/files/5542825/pod1.txt)
[volumes.txt](https://github.com/hpe-storage/csi-driver/files/5542840/volumes.txt)
