### ISSUE TITLE
Create clone from snapshot or clone from pvc fails "Body length 0" error

### ISSUE THREAD

**Issue by alexbarta** [hpe-storage/csi-driver#289]
Hi all,

I am using hpe csi driver 2.0.0 w/ Primera FC and w/ k8s 1.20.2
After enabling CSI snapshot 
```
git clone https://github.com/kubernetes-csi/external-snapshotter
cd external-snapshotter

# Kubernetes 1.20 and newer
git checkout tags/v4.0.0 -b release-4.0
```
and creating volumesnapshot class 
```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: hpe-snapshot
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: csi.hpe.com
deletionPolicy: Delete
parameters:
  description: "Snapshot created by the HPE CSI Driver"
  csi.storage.k8s.io/snapshotter-secret-name: hpe-backend
  csi.storage.k8s.io/snapshotter-secret-namespace: hpe-storage
  csi.storage.k8s.io/snapshotter-list-secret-name: hpe-backend
  csi.storage.k8s.io/snapshotter-list-secret-namespace: hpe-storage
```
I am able to create volume snapshot correctly
```
# k get pvc my-first-pvc1
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
my-first-pvc1   Bound    pvc-760bdebc-a625-4dd6-86f4-de7bce1af1c4   2Gi        RWO            hpe-primera    42h

# k get volumesnapshot
NAME           READYTOUSE   SOURCEPVC       SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
my-snapshot2   true         my-first-pvc1                           2Gi           hpe-snapshot    snapcontent-70a455b2-eba8-4400-8a95-de201ddecc3c   11s            12s
```
but a create a pvc from snap or pvc from pvc
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-from-snapshot
spec:
  dataSource:
    name: my-snapshot2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hpe-primera
```
I get this error

```
# k describe pvc my-pvc-from-snapshot
Name:          my-pvc-from-snapshot
Namespace:     default
StorageClass:  hpe-primera
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: csi.hpe.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
DataSource:
  APIGroup:  snapshot.storage.k8s.io
  Kind:      VolumeSnapshot
  Name:      my-snapshot2
Used By:     <none>
Events:
  Type     Reason                Age                From                                                            Message
  ----     ------                ----               ----                                                            -------
  Normal   Provisioning          24s (x6 over 86s)  csi.hpe.com_hpecp14.local_ae153ec4-f172-48bf-904d-e606c15ca7aa  External provisioner is provisioning volume for claim "default/my-pvc-from-snapshot"
  Warning  ProvisioningFailed    18s (x6 over 80s)  csi.hpe.com_hpecp14.local_ae153ec4-f172-48bf-904d-e606c15ca7aa  failed to provision volume with StorageClass "hpe-primera": rpc error: code = Internal desc = Failed to clone-create volume pvc-b894308c-aa0d-4656-b659-ea80809a8833, Post http://primera3par-csp-svc:8080/containers/v1/volumes: http: ContentLength=448 with Body length 0
  Normal   ExternalProvisioning  3s (x7 over 86s)   persistentvolume-controller                                     waiting for a volume to be created, either by external provisioner "csi.hpe.com" or manually created by system administrator

```
Sounds like the driver's waiting for somebody else to create an empty destination volume?
